(require 'go-mode)
(add-hook 'before-save-hook 'gofmt-before-save)
(add-hook 'go-mode-hook '(lambda ()
			   (local-set-key (kbd "C-c C-r") 'go-remove-unused-imports)))
(add-hook 'go-mode-hook '(lambda ()
			   (local-set-key (kbd "C-c C-g") 'go-goto-imports)))
(add-hook 'go-mode-hook '(lambda ()
			   (local-set-key (kbd "C-c C-f") 'gofmt)))
(add-hook 'go-mode-hook '(lambda ()
			   (local-set-key (kbd "C-c C-k") 'godoc)))
(add-hook 'go-mode-hook 'company-mode)
(add-hook 'go-mode-hook (lambda ()  (set (make-local-variable 'company-backends) '(company-go))
			  (company-mode)))
(require 'go-autocomplete)
(require 'auto-complete-config)
(ac-config-default)

(require 'go-playground)
(add-hook 'go-playground-mode-hook '(lambda ()
			   (local-set-key (kbd "C-c C-e") 'go-playground-exec)))
(add-hook 'go-playground-mode-hook '(lambda ()
			   (local-set-key (kbd "C-c C-r") 'go-playground-rm)))
